"""init

Revision ID: 63e57822e693
Revises: 
Create Date: 2026-07-07 21:33:33.153600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '63e57822e693'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('fuel_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fuel_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('network_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['public.networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'fuel_type', 'network_id', 'created_at', name='uq_fuelprice_source_fueltype_network'),
    schema='public'
    )
    op.create_geospatial_table('gas_stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('geog', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('network_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['public.networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_geospatial_index('idx_gas_stations_geog', 'gas_stations', ['geog'], unique=False, schema='public', postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_gas_stations_geog', table_name='gas_stations', schema='public', postgresql_using='gist', column_name='geog')
    op.drop_geospatial_table('gas_stations', schema='public')
    op.drop_table('fuel_prices', schema='public')
    op.drop_table('networks', schema='public')
    # ### end Alembic commands ###
